// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-todos.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function clientFor(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_todos_default = defineTool({
  name: "list_todos",
  title: "List todos",
  description: "List the signed-in user's active todos. Optionally filter by category (today, this_week, next_week, others) and/or workspace_id.",
  inputSchema: {
    category: z.enum(["today", "this_week", "next_week", "others"]).optional().describe("Filter to a single category."),
    workspace_id: z.string().uuid().optional().describe("Restrict to a workspace.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, workspace_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = clientFor(ctx);
    let query = supabase.from("todos").select("id, text, category, tags, notes, completed, workspace_id, created_at").eq("user_id", ctx.getUserId()).eq("removed", false).order("created_at", { ascending: false }).limit(200);
    if (category) query = query.eq("category", category);
    if (workspace_id) query = query.eq("workspace_id", workspace_id);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { todos: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-overdue-todos.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
function clientFor2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function partsInTz(date, timeZone) {
  const fmt = new Intl.DateTimeFormat("en-US", {
    timeZone,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    weekday: "short"
  });
  const parts = fmt.formatToParts(date);
  const get = (t) => parts.find((p) => p.type === t)?.value ?? "";
  const weekdayMap = {
    Sun: 0,
    Mon: 1,
    Tue: 2,
    Wed: 3,
    Thu: 4,
    Fri: 5,
    Sat: 6
  };
  return {
    year: Number(get("year")),
    month: Number(get("month")),
    day: Number(get("day")),
    weekday: weekdayMap[get("weekday")] ?? 0
  };
}
function dayDiff(a, b) {
  const au = Date.UTC(a.year, a.month - 1, a.day);
  const bu = Date.UTC(b.year, b.month - 1, b.day);
  return Math.round((bu - au) / 864e5);
}
var list_overdue_todos_default = defineTool2({
  name: "list_overdue_todos",
  title: "List overdue todos",
  description: "List the signed-in user's overdue active todos. A `today` task is overdue when its creation day is strictly before today. A `this_week` task is overdue when the current time is past the end of its creation week (Sunday 23:59:59 local). Other categories are never overdue.",
  inputSchema: {
    workspace_id: z2.string().uuid().optional().describe("Restrict to a workspace."),
    timezone: z2.string().optional().describe(
      "IANA timezone (e.g. 'America/Santiago') used to compute day/week boundaries. Defaults to 'UTC'."
    )
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ workspace_id, timezone }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const tz = timezone ?? "UTC";
    try {
      new Intl.DateTimeFormat("en-US", { timeZone: tz });
    } catch {
      return {
        content: [{ type: "text", text: `Invalid timezone: ${tz}` }],
        isError: true
      };
    }
    const supabase = clientFor2(ctx);
    let query = supabase.from("todos").select("id, text, category, tags, notes, workspace_id, created_at").eq("user_id", ctx.getUserId()).eq("removed", false).eq("completed", false).in("category", ["today", "this_week"]).order("created_at", { ascending: false }).limit(500);
    if (workspace_id) query = query.eq("workspace_id", workspace_id);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const now = /* @__PURE__ */ new Date();
    const nowParts = partsInTz(now, tz);
    const overdue = (data ?? []).filter((t) => {
      if (!t.created_at) return false;
      const created = new Date(t.created_at);
      const cp = partsInTz(created, tz);
      if (t.category === "today") {
        return dayDiff(cp, nowParts) > 0;
      }
      if (t.category === "this_week") {
        const daysToSunday = cp.weekday === 0 ? 0 : 7 - cp.weekday;
        return dayDiff(cp, nowParts) > daysToSunday;
      }
      return false;
    });
    return {
      content: [{ type: "text", text: JSON.stringify(overdue, null, 2) }],
      structuredContent: { todos: overdue }
    };
  }
});

// src/lib/mcp/tools/create-todo.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
function clientFor3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_todo_default = defineTool3({
  name: "create_todo",
  title: "Create todo",
  description: "Create a new todo for the signed-in user. If workspace_id is omitted, the user's default workspace is used.",
  inputSchema: {
    text: z3.string().trim().min(1).max(500).describe("Task text."),
    category: z3.enum(["today", "this_week", "next_week", "others"]).default("today").describe("Category bucket."),
    workspace_id: z3.string().uuid().optional().describe("Target workspace."),
    tags: z3.array(z3.string()).optional().describe("Optional tags."),
    notes: z3.string().optional().describe("Optional notes.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ text, category, workspace_id, tags, notes }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = clientFor3(ctx);
    const userId = ctx.getUserId();
    let wsId = workspace_id;
    if (!wsId) {
      const { data: ws } = await supabase.from("workspaces").select("id, is_default, position").eq("user_id", userId).order("position", { ascending: true });
      const chosen = ws?.find((w) => w.is_default) ?? ws?.[0];
      if (!chosen) {
        return { content: [{ type: "text", text: "No workspace available" }], isError: true };
      }
      wsId = chosen.id;
    }
    const { data, error } = await supabase.from("todos").insert({
      user_id: userId,
      workspace_id: wsId,
      text,
      category,
      tags: tags ?? null,
      notes: notes ?? null
    }).select("id, text, category, workspace_id").single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Created todo ${data.id}: ${data.text}` }],
      structuredContent: { todo: data }
    };
  }
});

// src/lib/mcp/tools/update-todo.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^3.25.76";
function clientFor4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var update_todo_default = defineTool4({
  name: "update_todo",
  title: "Update todo",
  description: "Update fields of an existing todo owned by the signed-in user. Provide only the fields to change; omitted fields are left untouched. `text` is the task title, `notes` is the description, `tags` replaces the tag list, and `urls` replaces the links list.",
  inputSchema: {
    id: z4.string().uuid().describe("Todo id."),
    text: z4.string().trim().min(1).max(500).optional().describe("Task title."),
    notes: z4.string().optional().describe("Task description / notes."),
    tags: z4.array(z4.string()).optional().describe("Replacement tag list."),
    urls: z4.array(z4.string().url()).optional().describe("Replacement list of links (URLs).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, text, notes, tags, urls }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const patch = {};
    if (text !== void 0) patch.text = text;
    if (notes !== void 0) patch.notes = notes;
    if (tags !== void 0) patch.tags = tags;
    if (urls !== void 0) patch.urls = urls;
    if (Object.keys(patch).length === 0) {
      return { content: [{ type: "text", text: "No fields provided to update." }], isError: true };
    }
    const supabase = clientFor4(ctx);
    const { data, error } = await supabase.from("todos").update(patch).eq("id", id).eq("user_id", ctx.getUserId()).select("id, text, notes, tags, urls, category, workspace_id, completed, created_at, updated_at").maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Todo not found" }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Updated todo ${data.id}` }],
      structuredContent: { todo: data }
    };
  }
});

// src/lib/mcp/tools/complete-todo.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z5 } from "npm:zod@^3.25.76";
function clientFor5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var complete_todo_default = defineTool5({
  name: "complete_todo",
  title: "Complete todo",
  description: "Mark a todo as complete (or set completed=false to reopen it).",
  inputSchema: {
    id: z5.string().uuid().describe("Todo id."),
    completed: z5.boolean().default(true).describe("Completion state.")
  },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, completed }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = clientFor5(ctx);
    const { data, error } = await supabase.from("todos").update({
      completed,
      completed_at: completed ? (/* @__PURE__ */ new Date()).toISOString() : null
    }).eq("id", id).eq("user_id", ctx.getUserId()).select("id, text, completed").maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Todo not found" }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Todo ${data.id} completed=${data.completed}` }],
      structuredContent: { todo: data }
    };
  }
});

// src/lib/mcp/tools/list-workspaces.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.22.2";
function clientFor6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_workspaces_default = defineTool6({
  name: "list_workspaces",
  title: "List workspaces",
  description: "List the signed-in user's workspaces.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = clientFor6(ctx);
    const { data, error } = await supabase.from("workspaces").select("id, name, is_default, position").eq("user_id", ctx.getUserId()).order("position", { ascending: true });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { workspaces: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "plygdadnsjdmwqdhntad";
var mcp_default = defineMcp({
  name: "owldone-mcp",
  title: "OwlDone",
  version: "0.1.0",
  instructions: "Tools for OwlDone, a personal task manager. Use `list_workspaces` to discover workspaces, `list_todos` to read active tasks (optionally filtered by category or workspace), `list_overdue_todos` to read tasks that are past due (accepts an optional IANA `timezone` such as 'America/Santiago' \u2014 defaults to UTC), `create_todo` to add new tasks, `update_todo` to edit an existing task's title (`text`), description (`notes`), `tags`, or links (`urls`), and `complete_todo` to mark tasks done. Categories are: today, this_week, next_week, others.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_workspaces_default, list_todos_default, list_overdue_todos_default, create_todo_default, update_todo_default, complete_todo_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
