// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-todos.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function clientFor(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_todos_default = defineTool({
  name: "list_todos",
  title: "List todos",
  description: "List the signed-in user's active todos. Optionally filter by category (today, this_week, next_week, others) and/or workspace_id.",
  inputSchema: {
    category: z.enum(["today", "this_week", "next_week", "others"]).optional().describe("Filter to a single category."),
    workspace_id: z.string().uuid().optional().describe("Restrict to a workspace.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, workspace_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = clientFor(ctx);
    let query = supabase.from("todos").select("id, text, category, tags, notes, completed, workspace_id, created_at").eq("user_id", ctx.getUserId()).eq("removed", false).order("created_at", { ascending: false }).limit(200);
    if (category) query = query.eq("category", category);
    if (workspace_id) query = query.eq("workspace_id", workspace_id);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { todos: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-todo.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
function clientFor2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_todo_default = defineTool2({
  name: "create_todo",
  title: "Create todo",
  description: "Create a new todo for the signed-in user. If workspace_id is omitted, the user's default workspace is used.",
  inputSchema: {
    text: z2.string().trim().min(1).max(500).describe("Task text."),
    category: z2.enum(["today", "this_week", "next_week", "others"]).default("today").describe("Category bucket."),
    workspace_id: z2.string().uuid().optional().describe("Target workspace."),
    tags: z2.array(z2.string()).optional().describe("Optional tags."),
    notes: z2.string().optional().describe("Optional notes.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ text, category, workspace_id, tags, notes }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = clientFor2(ctx);
    const userId = ctx.getUserId();
    let wsId = workspace_id;
    if (!wsId) {
      const { data: ws } = await supabase.from("workspaces").select("id, is_default, position").eq("user_id", userId).order("position", { ascending: true });
      const chosen = ws?.find((w) => w.is_default) ?? ws?.[0];
      if (!chosen) {
        return { content: [{ type: "text", text: "No workspace available" }], isError: true };
      }
      wsId = chosen.id;
    }
    const { data, error } = await supabase.from("todos").insert({
      user_id: userId,
      workspace_id: wsId,
      text,
      category,
      tags: tags ?? null,
      notes: notes ?? null
    }).select("id, text, category, workspace_id").single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Created todo ${data.id}: ${data.text}` }],
      structuredContent: { todo: data }
    };
  }
});

// src/lib/mcp/tools/complete-todo.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
function clientFor3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var complete_todo_default = defineTool3({
  name: "complete_todo",
  title: "Complete todo",
  description: "Mark a todo as complete (or set completed=false to reopen it).",
  inputSchema: {
    id: z3.string().uuid().describe("Todo id."),
    completed: z3.boolean().default(true).describe("Completion state.")
  },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, completed }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = clientFor3(ctx);
    const { data, error } = await supabase.from("todos").update({
      completed,
      completed_at: completed ? (/* @__PURE__ */ new Date()).toISOString() : null
    }).eq("id", id).eq("user_id", ctx.getUserId()).select("id, text, completed").maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Todo not found" }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Todo ${data.id} completed=${data.completed}` }],
      structuredContent: { todo: data }
    };
  }
});

// src/lib/mcp/tools/list-workspaces.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
function clientFor4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_workspaces_default = defineTool4({
  name: "list_workspaces",
  title: "List workspaces",
  description: "List the signed-in user's workspaces.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = clientFor4(ctx);
    const { data, error } = await supabase.from("workspaces").select("id, name, is_default, position").eq("user_id", ctx.getUserId()).order("position", { ascending: true });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { workspaces: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "plygdadnsjdmwqdhntad";
var mcp_default = defineMcp({
  name: "owldone-mcp",
  title: "OwlDone",
  version: "0.1.0",
  instructions: "Tools for OwlDone, a personal task manager. Use `list_workspaces` to discover workspaces, `list_todos` to read active tasks (optionally filtered by category or workspace), `create_todo` to add new tasks, and `complete_todo` to mark tasks done. Categories are: today, this_week, next_week, others.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_workspaces_default, list_todos_default, create_todo_default, complete_todo_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
